#ApplicationURL
URL = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
#Browser details
browserName = chrome
##Login Credentials
username = Admin
password = admin123
##Timeouts(in seconds)
pageLoadTimeout = 20
implicitWait = 10